plugins {
    id 'com.android.application'
}

android {
    namespace 'design.lihanyang673.frogstep'
    compileSdk 34

    defaultConfig {
        applicationId "design.lihanyang673.frogstep"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
